export const theme = {
  color: {
    primary: "#4340D6",
    green: "#00cb6a",
    yellow: "#f3ba2f",
    white: "white",
    black: "black",
    red: "#f26666",
  },
  spacings: {
    tiny: 8,
    smallest: 10,
    smaller: 12,
    small: 14,
    medium: 16,
    big: 24,
    bigger: 30,
    biggest: 40,
    huge: 50,
  },
  text: {
    tiny: 8,
    smallest: 10,
    smaller: 12,
    small: 14,
    medium: 15,
    big: 16,
    bigger: 20,
    biggest: 24,
    huge: 32,

    bold: "Roboto_700Bold",
    semiBold: "Roboto_500Medium",
    regular: "Roboto_400Regular",
  },
};
